name: dia_etl_env
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5
  - appnope=0.1.4
  - asttokens=3.0.1
  - atk-1.0=2.38.0
  - brotli=1.2.0
  - brotli-bin=1.2.0
  - bzip2=1.0.8
  - ca-certificates=2026.1.4
  - cairo=1.18.4
  - cairomm=1.16.2
  - cairomm-1.16=1.16.2
  - cffi=1.17.1
  - comm=0.2.3
  - contourpy=1.3.3
  - cycler=0.12.1
  - debugpy=1.8.16
  - decorator=5.2.1
  - epoxy=1.5.10
  - executing=2.2.1
  - expat=2.7.3
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.61.1
  - freetype=2.14.1
  - fribidi=1.0.16
  - gdk-pixbuf=2.44.4
  - gettext=0.25.1
  - gettext-tools=0.25.1
  - glib-tools=2.86.3
  - gmp=6.3.0
  - graph-tool=2.98
  - graph-tool-base=2.98
  - graphite2=1.3.14
  - gtk3=3.24.43
  - harfbuzz=12.3.2
  - hicolor-icon-theme=0.17
  - icu=78.2
  - ipykernel=7.1.0
  - ipython=9.9.0
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - jupyter_client=8.8.0
  - jupyter_core=5.9.1
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lcms2=2.18
  - lerc=4.0.0
  - libasprintf=0.25.1
  - libasprintf-devel=0.25.1
  - libblas=3.11.0
  - libboost=1.86.0
  - libboost-python=1.86.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcblas=3.11.0
  - libcxx=21.1.8
  - libdeflate=1.25
  - libedit=3.1.20250104
  - libexpat=2.7.3
  - libffi=3.4.4
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgettextpo=0.25.1
  - libgettextpo-devel=0.25.1
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libgirepository=1.84.0
  - libglib=2.86.3
  - libiconv=1.18
  - libintl=0.25.1
  - libintl-devel=0.25.1
  - libjpeg-turbo=3.1.2
  - liblapack=3.11.0
  - liblzma=5.8.2
  - liblzma-devel=5.8.2
  - libopenblas=0.3.30
  - libpng=1.6.54
  - librsvg=2.60.0
  - libsodium=1.0.20
  - libsqlite=3.51.2
  - libtiff=4.7.1
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxml2-16=2.15.1
  - libzlib=1.3.1
  - llvm-openmp=21.1.8
  - matplotlib-base=3.10.8
  - matplotlib-inline=0.2.1
  - munkres=1.1.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - numpy=2.4.1
  - openjpeg=2.5.4
  - openssl=3.6.1
  - packaging=25.0
  - pango=1.56.4
  - parso=0.8.5
  - pcre2=10.46
  - pexpect=4.9.0
  - pillow=12.1.0
  - pip=25.3
  - pixman=0.46.4
  - platformdirs=4.5.1
  - prompt-toolkit=3.0.52
  - psutil=7.0.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pycairo=1.29.0
  - pycparser=2.22
  - pygments=2.19.2
  - pygobject=3.50.0
  - pyparsing=3.3.2
  - python=3.11.11
  - python-dateutil=2.9.0.post0
  - python_abi=3.11
  - pyzmq=27.1.0
  - qhull=2020.2
  - readline=8.3
  - scipy=1.17.0
  - setuptools=80.10.1
  - sigcpp-3.0=3.6.0
  - six=1.17.0
  - sparsehash=2.0.4
  - sqlite=3.51.1
  - stack_data=0.6.3
  - tk=8.6.15
  - tornado=6.5.4
  - traitlets=5.14.3
  - typing_extensions=4.15.0
  - tzdata=2025c
  - unicodedata2=17.0.0
  - wcwidth=0.5.0
  - wheel=0.46.3
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xextproto=7.3.0
  - xz=5.8.2
  - xz-gpl-tools=5.8.2
  - xz-tools=5.8.2
  - zeromq=4.3.5
  - zlib=1.3.1
  - zlib-ng=2.3.2
  - zstandard=0.25.0
  - zstd=1.5.7
  - pip:
      - branca==0.8.2
      - certifi==2026.1.4
      - charset-normalizer==3.4.4
      - folium==0.20.0
      - idna==3.11
      - jinja2==3.1.6
      - markupsafe==3.0.3
      - pandas==3.0.0
      - psycopg2==2.9.11
      - requests==2.32.5
      - urllib3==2.6.3
      - xyzservices==2025.11.0
prefix: /opt/miniconda3/envs/dia_etl_env
